### PR TITLE
Minecraft 1.20.2 (Fabric at least)

### PR DESCRIPTION
**Pull request by RubixDev**
This PR updates the mod to support Minecraft 1.20.2 on Fabric. It is based on the diff by @offbeat-stuff in https://github.com/Lizard-Of-Oz/Inventorio/issues/275, but required some more changes. Most notably, the sprite loading for `ButtonTextures` seems to have changed quite a bit, so it looks like those textures now have to all be in their own separate files.

### CODE REVIEW

**Comment by Lizard-Of-Oz** [comment]
Thank you! I'll check it out later today.

**Comment by Lizard-Of-Oz** [comment]
Can confirm that it works fine on 1.20.2, but on later versions that same jar crashes because Minecraft's obfuscated classes have shifted, so, it'd require a new gradle config and a recompile.

**Comment by Lizard-Of-Oz** [comment]
Would you like if I'd upload the 1.20.2 update to CurseForge? With proper credit of course.

**Comment by RubixDev** [comment]
> Can confirm that it works fine on 1.20.2, but on later versions that same jar crashes because Minecraft's obfuscated classes have shifted, so, it'd require a new gradle config and a recompile.

Yea I kind of assumed that. I only updated to 1.20.2 for now because I'm currently still playing on that version.

> Would you like if I'd upload the 1.20.2 update to CurseForge? With proper credit of course.

Yes sure, go ahead! That's exactly why I finally made this PR, to share a 1.20.2 version with others and not just keep it to myself as I have for the past few weeks :sweat_smile:. Also Modrinth releases would be great too, it's really not that much effort. This is one of the last 5 mods I'm using that isn't on Modrinth yet.

**Comment by offbeat-stuff** [comment]
cant wait for 1.20.4

**Pull request merged**
