### PR TITLE
Create de_de.json

### PR DESCRIPTION
**Pull request by Cape-City**
German Translation

### CODE REVIEW

**Comment by Lizard-Of-Oz** [comment]
Thanks! Will merge in once 1.20 is out - I need a break from the mod.

**Comment by Cape-City** [comment]
So much work with it? It's a big mod, which overhauled a big of the minecraft experience!

**Comment by Lizard-Of-Oz** [comment]
It takes a lot of time to test that nothing broke in the process. Broken configs of today's release was a good example of missing something even _despite_ extensive tests.

**Comment by Lizard-Of-Oz** [comment]
Added German translation. Thank you.

**Pull request closed without merging**
