### PR TITLE
Minecraft 1.20.4 and NeoForge

### PR DESCRIPTION
**Pull request by RubixDev**
This PR ports the mod to Minecraft 1.20.4 and replaces the forge subproject with a neoforge subproject.

On the Fabric side the port was very simple. The 1.20.2 version already worked except for the removal of `AbstractGlassBlock` which was used in a test for using silk touch tools. That check was now replaced with a test whether the block is a `StainedGlassBlock` or the normal glass block.

The NeoForge update required a bit more work, mainly due to these two large refactors in NeoForge: https://github.com/neoforged/NeoForge/pull/277 (Network refactoring) and https://github.com/neoforged/NeoForge/pull/257 (Registry rework).

This is still pretty much my first ever experience with working with (Neo)Forge and Architectury, so I can't guarantee that I haven't made any stupid beginner mistakes.

### CODE REVIEW

**Comment by Lizard-Of-Oz** [comment]
I'll get to it tomorrow, and will then upload to CurseForge, and, hopefully, Modrinth too.

**Comment by offbeat-stuff** [comment]
Oh nice, cant wait to test this.

Ill try and test this now

**Comment by offbeat-stuff** [comment]
hmm cant seem to build this, can you tell how to build it?

**Comment by offbeat-stuff** [comment]
ok got it the build is in subfolders fabric/ forge/

**Comment by Lizard-Of-Oz** [comment]
```diff
plugins {
-    id "architectury-plugin" version "3.4.143"
-    id "dev.architectury.loom" version "0.12.0.301" apply false
+    id "architectury-plugin" version "3.4-SNAPSHOT"
+    id "dev.architectury.loom" version "1.5-SNAPSHOT" apply false
```
I remember deliberately moving from snapshots to specific versions to avoid an issue, but I no longer remember what that issue was. Something related to the building process. I guess, keep the change but put a pin on it.

**Comment by Lizard-Of-Oz** [comment]
Uploaded to CurseForge. I hope to find time to upload to Modrinth in the following days.

- Checked Fabric on a client-server setup: everything seems to work fine.

- Checked NeoForge on a client-hosted world because I couldn't get a dedicated server running, so I can't test if there's any client-server desync.
   - Swapped Hands (the feature that makes binds the hotbar to your off-hand) doesn't work correctly on NeoForge. The player avatar _thinks_ the hands have been swapped, but trying to place blocks or use items causes a desync and the world acts as if your hands are not switched.

**Comment by RubixDev** [comment]
Thanks!

> Swapped Hands (the feature that makes binds the hotbar to your off-hand) doesn't work correctly on NeoForge. The player avatar thinks the hands have been swapped, but trying to place blocks or use items causes a desync and the world acts as if your hands are not switched.

I'll take a look later; forgot to test that feature.

**Pull request merged**
