### PR TITLE
Port to 1.18.2

### PR DESCRIPTION
**Pull request by truemogician**
Port this mod to 1.18.2, for both Forge and Fabric.  
- Upgrade dependencies to proper versions
- Adapt to the new Forge API, and replace some deprecated code for Fabric.  
- Some warnings are also fixed in passing.

### CODE REVIEW

**Comment by truemogician** [comment]
#112 could be closed after merging

**Comment by Lizard-Of-Oz** [comment]
Thanks. I will proceed with testing and merging tomorrow (approx. after 24 hours).

**Comment by maxface14** [comment]
What does this mean for users? Do you have an upper bound for when the 1.18.2 Fabric port will be available to the public?

(No rush I'm just curious)

**Comment by truemogician** [comment]
@maxface14 It's up to the author. After his reviewing and merging this pull request, the release will soon be published I suppose. If you can't wait to have a try, you may build one from [my forked repository](https://github.com/truemogician/Inventorio/tree/1.18.2).

**Comment by Lizard-Of-Oz** [comment]
@maxface14 Testing right now, and hopefully will publish the builds in 2..3 hours.

**Comment by Lizard-Of-Oz** [comment]
Glad to inform everyone that it's finally out, thanks to @truemogician!

**Pull request closed without merging**
